---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: uat
spec:
  hard:
    request.cpu: "1"
    request.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kin: Deployment
metadata:
  namespace: uat
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
    template:
      metadata:
        labels:
          app: front
      spec:
        containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: 500M
              cpu: 500m
            limits:
              memory: 500M
              cpu: 500m       