apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: test-node
        image: node-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000